[input.footprint]
path = '/home/ravi/git/roofer/roofer_data/yoc-2019-completely-new.gpkg'
bid = "identificatie"

[[input.pointclouds]]
name = "AHN3"
date = 2014
quality = 1
path = '/home/ravi/git/roofer/roofer_data/yoc-2019-completely-new-ahn3.laz'

[[input.pointclouds]]
name = "AHN4"
date = 2020
quality = 0
path = '/home/ravi/git/roofer/roofer_data/yoc-2019-completely-new-ahn4.laz'

[[input.pointclouds]]
name = "KAD2020"
date = 2020
quality = 2
path = '/home/ravi/git/roofer/roofer_data/yoc-2019-completely-new-kadaster.laz'

[parameters]
cellsize = 0.5

[output]
path = '/output/test_all/'

# {bid} will be replaced by building identifier
# {pc_name} will be replaced by input pointcloud name
# {path} will be replaced by path
building_toml_file = '{path}/0/objects/{bid}/crop/config{pc_name}.toml'
building_las_file = '{path}/0/objects/{bid}/crop/{bid}_{pc_name}.las'
building_raster_file = '{path}/0/objects/{bid}/crop/{bid}_{pc_name}.tif'
building_gpkg_file = '{path}/0/objects/{bid}/crop/{bid}.gpkg'
building_jsonl_file = '{path}/0/objects/{bid}/reconstruct/{pc_name}_{bid}.city.jsonl'

metadata_json_file = '{path}/0/metadata.json'
jsonl_list_file = '{path}/0/features_{pc_name}.txt'
index_file = '{path}/0/index.gpkg'

# these get passed through to the geoflow config files that are generated for each building
[output.reconstruction_parameters]
GF_PROCESS_CRS="EPSG:7415"
OUTPUT_CRS="EPSG:7415"

line_detect__epsilon=1.000000
lod13__step_height=3.000000
optimisation_data_term=8.000000
plane_detect__k=15
plane_detect__epsilon=0.300000
plane_detect__min_points=15
plane_detect__normal_angle=0.750000
thres_alpha=0.250000
thres_reg_line_dist=0.800000
thres_reg_line_ext=3.000000
clip_ground=true
lod1_extrude_to_max=false