polygon-source = "data/wippolder/wippolder.gpkg"
output-directory = 'output/wippolder'

[[pointclouds]]
name = "AHN3"
source = "data/wippolder/wippolder.laz"

[output-attributes]
status = "rf_status"
reconstruction_time = "rf_reconstruction_time"
val3dity_lod12 = "rf_val3dity_lod12"
val3dity_lod13 = "rf_val3dity_lod13"
val3dity_lod22 = "rf_val3dity_lod22"
is_glass_roof = "rf_is_glass_roof"
nodata_frac = "rf_nodata_frac"
nodata_r = "rf_nodata_r"
pt_density = "rf_pt_density"
is_mutated = "rf_is_mutated"
pc_select = "rf_pc_select"
pc_source = "rf_pc_source"
pc_year = "rf_pc_year"
force_lod11 = "rf_force_lod11"
roof_type = "rf_roof_type"
roof_elevation_50p = "rf_roof_elevation_50p"
roof_elevation_70p = "rf_roof_elevation_70p"
roof_elevation_min = "rf_roof_elevation_min"
roof_elevation_max = "rf_roof_elevation_max"
rmse_lod12 = "rf_rmse_lod12"
rmse_lod13 = "rf_rmse_lod13"
rmse_lod22 = "rf_rmse_lod22"
h_ground = "rf_h_ground"
