name: Documentation

on:
  push:
    tags:
      - "*"
    branches: [ develop, feature/ci ]
jobs:
  deploy:
    name: Build and publish documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install Docs
        run: |
          sudo apt-get install doxygen graphviz
          pip install jinja2 Pygments

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        shell: bash
        run: |
          echo "BUILD_OUTPUT_DIR=${{ github.workspace }}/build" >> "$GITHUB_ENV"
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV

      - uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Update vcpkg baseline
        run: vcpkg x-update-baseline

      - name: Configure CMake
        run: >
          cmake -B ${{ env.BUILD_OUTPUT_DIR }}
          --preset vcpkg-minimal
          -S ${{ github.workspace }}

      - name: Build
        run: |
          cmake --build ${{ env.BUILD_OUTPUT_DIR }} --config Debug --target docs -j4
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
