name: Documentation

on:
  push:
    tags:
      - "*"
    branches: [ "develop" ]
    pull_request:
      branches: [ "develop" ]
jobs:
  deploy:
    name: Build and publish documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install python dependencies
        run: |
          pip install -r "${{ github.workspace }}/requirements.txt"
          pip install -r "${{ github.workspace }}/docs/requirements.txt"

      - name: Set reusable strings
        # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
        shell: bash
        run: |
          echo "VCPKG_ROOT=$VCPKG_INSTALLATION_ROOT" >> $GITHUB_ENV
          echo "pybind11_ROOT=$(python -m pybind11 --cmakedir)" >> $GITHUB_ENV

      - uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Update vcpkg baseline
        run: vcpkg x-update-baseline

      - name: Configure CMake
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B build
          --preset vcpkg-docs
          -S ${{ github.workspace }}

      - name: Generate Docs
        run: |
          sudo apt-get install doxygen graphviz
          mkdir docs/rooferpy
          cp Build/rooferpy/*.so docs/rooferpy
          cd docs
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/docs/_build/html
          publish_branch: gh-pages
