name: Documentation

on:
  push:
    tags:
      - "*"
    branches: [ develop, feature/ci ]
jobs:
  deploy:
    name: Build and publish documentation
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: Install Docs
        run: |
          sudo apt-get install doxygen graphviz
          pip install jinja2 Pygments

      - name: Compile
        working-directory: ${{ github.workspace }}/docs
        run: doxygen

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ github.workspace }}/docs/html
          publish_branch: gh-pages
