name: Formatting

on:
  push:
    branches: [ develop, feature/project-tools-refactor, feature/ci ]
  pull_request:
    branches: [ develop ]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.1
